Repository ManageIQ/ui-components, pull requests merged in 2018-09, with the labels that each got.

#341 Ensure DialogFieldDateTimeControl fields are properly initialized
  src/dialog-user/components/dialog-user/dialogField.ts
Labels: blocker, bug, gaprindashvili/yes

#343 toolbar - fix includes of undefined for custom buttons
  src/toolbar/components/toolbar-menu/toolbarComponent.ts
Labels: bug, gaprindashvili/no

#338 [GAPRINDASHVILI] Add translations for gaprindashvili
  locale/es/ui-components.po
  locale/fr/ui-components.po
  locale/ja/ui-components.po
  locale/pt_BR/ui-components.po
  locale/zh_CN/ui-components.po
Labels: blocker, internationalization

#347 Update dynamic fields responders after change
  src/dialog-editor/components/abstractModal.ts
  src/dialog-editor/components/box/box.html
  src/dialog-editor/components/modal-field/field.html
  src/dialog-editor/components/modal/modalComponent.ts
Labels: blocker, bug, gaprindashvili/yes

#346 Remove datatables dependencies
  demo/template-index.ejs
  package.json
  src/styles/ui-components.scss
  src/styles/vendor.scss
Labels: technical debt
