Repository ManageIQ/ui-components, pull requests merged in 2018-02, with the labels that each got.

#250 Fix for default value on dropdown inside dialog not storing value
  src/dialog-editor/components/field/field.html
  src/dialog-editor/components/field/fieldComponent.spec.ts
  src/dialog-editor/components/field/fieldComponent.ts
  src/dialog-editor/components/modal-field-template/drop-down-list.html
  src/dialog-user/components/dialog-user/dialogField.html
  src/dialog-user/components/dialog-user/dialogField.spec.ts
  src/dialog-user/components/dialog-user/dialogField.ts
Labels: blocker, bug, gaprindashvili/yes

#251 Corrected type for initial values
  src/dialog-editor/components/modal-field-template/radio-button.html
  src/dialog-editor/components/toolbox/toolboxComponent.ts
Labels: blocker, bug, gaprindashvili/yes

#253 Set ng-change for tag control options
  src/dialog-editor/components/abstractModal.ts
  src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
  src/dialog-editor/components/modal-field-template/tag-control.html
  src/dialog-editor/components/modal-field/field.html
  src/dialog-editor/components/modal/modalComponent.spec.ts
  src/dialog-editor/components/modal/modalComponent.ts
Labels: blocker, bug, gaprindashvili/yes

#255 Add missing code to make the dialog editor working in the demo
  demo/controllers/dialogEditorController.ts
  demo/views/dialog/editor.html
Labels: bug, gaprindashvili/no

#254 Update Bower dev CI to install dependencies before releasing
  ci/bower-dev.sh
Labels: bug, gaprindashvili/yes

#256 Drop the unnecessary visible binding from dialogEditorModal component
  demo/controllers/dialogEditorController.ts
  demo/views/dialog/editor.html
  src/dialog-editor/components/modal/modalComponent.ts
Labels: cleanup, refactoring

#258 Enabled select list to save values on change
  src/dialog-user/components/dialog-user/dialogField.html
Labels: bug, gaprindashvili/yes

#261 Add bootstrap-select to vendor dependencies
  src/vendor.ts
Labels: bug

#257 Create a top-level dialog editor component
  demo/controllers/dialogEditorController.ts
  demo/views/dialog/editor.html
  src/dialog-editor/components/dialog-editor/dialog-editor.html
  src/dialog-editor/components/dialog-editor/dialogEditorComponent.ts
  src/dialog-editor/components/dialog-editor/index.ts
  src/dialog-editor/components/index.ts
Labels: refactoring

#263 Add quadicon into report data, small tile and big tile
  demo/data/data-table.json
  src/gtl/components/tile-view/tile-view.html
Labels: enhancement, gaprindashvili/no

#265 Updated support for sorting of drop downs
  src/dialog-user/components/dialog-user/dialogField.spec.ts
  src/dialog-user/services/dialogData.spec.ts
  src/dialog-user/services/dialogData.ts
Labels: blocker, bug, gaprindashvili/yes
