Repository ManageIQ/ui-components, pull requests merged in 2018-04, with the labels that each got.

#276 Setting the default_value for TagControl dialog field
  src/dialog-user/components/dialog-user/dialogField.ts
Labels: bug

#267 When no checkboxes are visible in GTL hide select all
  src/gtl/components/data-table/data-table.html
  src/gtl/components/data-table/dataTableComponent.spec.ts
  src/gtl/components/pagination/pagination.html
  src/gtl/components/pagination/paginationComponent.spec.ts
  src/gtl/components/pagination/paginationComponent.ts
  src/gtl/components/tile-view/tile-view.html
  src/gtl/components/tile-view/tileViewComponent.spec.ts
  src/gtl/interfaces/abstractDataViewClass.ts
Labels: bug

#278 Fix for Catalog Item with Tag Control element cannot be ordered
  src/dialog-user/services/dialogData.spec.ts
  src/dialog-user/services/dialogData.ts
Labels: bug, gaprindashvili/yes

#279 Fix for default value containing all values of a list instead of single value
  src/dialog-user/components/dialog-user/dialogUser.spec.ts
  src/dialog-user/components/dialog-user/dialogUser.ts
Labels: blocker, bug, gaprindashvili/yes

#285 Fix travis failing on $.fn.dropdown.Constructor undefined from new bootstrap-select
  src/vendor.ts
Labels: gaprindashvili/yes, test

#282 fix cutoff dropdowns
  src/dialog-user/components/dialog-user/dialogField.html
Labels: blocker, bug, gaprindashvili/yes

#286 Fix for dynamic checkbox not updating properly
  src/dialog-user/services/dialogData.spec.ts
  src/dialog-user/services/dialogData.ts
Labels: blocker, bug, gaprindashvili/yes

#290 Update typescript to 2.8, fixing the build
  package.json
  src/dialog-user/services/dialogData.ts
  webpack.config.js
  webpack.vendor.config.js
Labels: build, gaprindashvili/no

#291 Use the name of the category that comes from the API as category_name
  src/dialog-editor/components/modal/modalComponent.spec.ts
  src/dialog-editor/components/modal/modalComponent.ts
Labels: bug, gaprindashvili/yes

#292 Fix for default value being set incorrectly for non 'DialogFieldSortedItem' field types
  src/dialog-user/components/dialog-user/dialogUser.spec.ts
  src/dialog-user/components/dialog-user/dialogUser.ts
Labels: blocker, bug, gaprindashvili/yes
