Repository ManageIQ/ui-components, pull requests merged in 2018-10, with the labels that each got.

#348 [HAMMER] Update i18n catalog for hammer
  locale/zanata.xml
Labels: internationalization

#349 Bower cleanup
  .eslintrc.json
  .gitignore
  .npmignore
  .travis.yml
  bower.json
  ci/bower-dev.sh
Labels: hammer/yes

#350 Remove unused moment & rx* dependencies
  package.json
  webpack.config.js
Labels: dependencies, technical debt
