Repository ManageIQ/ui-components, pull requests merged in 2018-03, with the labels that each got.

#268 Do not open browser when running tests
  karma.conf.js
  webpack.config.js
Labels: developer, enhancement

#266 Add ability to live-search dialog drop down fields
  src/dialog-user/components/dialog-user/dialogField.html
Labels: blocker, bug, gaprindashvili/yes

#269 Removed label and description of dialog from dialog-user
  src/dialog-user/components/dialog-user/dialog.html
Labels: bug, gaprindashvili/yes, ux/approved

#270 Fix for drop-down selection on dialogs while ordering service catalog having to select an item twice
  src/dialog-user/services/dialogData.ts
Labels: blocker, bug, gaprindashvili/yes

#271 Style correction for dialog dropdowns
  src/dialog-editor/components/box/box.html
  src/styles/dialog-editor-boxes.scss
Labels: bug, gaprindashvili/yes

#272 Ensure 'null' default values do not get coerced into 'NaN' for integer type drop downs
  src/dialog-user/services/dialogData.spec.ts
  src/dialog-user/services/dialogData.ts
Labels: blocker, bug, gaprindashvili/yes

#275 Track by $index ensures no duplicates in select list
  src/dialog-user/components/dialog-user/dialogField.html
Labels: blocker, bug, gaprindashvili/yes
