Repository ManageIQ/ui-components, pull requests merged in 2018-07, with the labels that each got.

#313 Added a functionality to sort dropdown values manualy (master)
  src/dialog-editor/components/modal-field-template/drop-down-list.html
  src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.spec.ts
  src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Labels: enhancement, gaprindashvili/no

#316 Fixed issue where options were being duplicated in dialogs
  src/dialog-user/components/dialog-user/dialogField.html
Labels: blocker, bug, gaprindashvili/yes

#317 Use separate 'changesHappened' update call for datetimepicker
  src/dialog-user/components/dialog-user/dialogField.html
  src/dialog-user/components/dialog-user/dialogField.spec.ts
  src/dialog-user/components/dialog-user/dialogField.ts
  src/dialog-user/services/dialogData.spec.ts
  src/dialog-user/services/dialogData.ts
Labels: blocker, bug, gaprindashvili/yes

#315 [GAPRINDASHVILI] Corrected description / values for dropdown list
  src/dialog-editor/components/modal-field-template/drop-down-list.html
  src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Labels: bug, gaprindashvili/yes

#322 Add missing gettext annotations
  package.json
  src/dialog-editor/components/field/field.html
  src/dialog-editor/components/modal-field-template/drop-down-list.html
  src/dialog-editor/components/modal-field-template/radio-button.html
  src/dialog-editor/components/modal-field-template/tag-control.html
  src/dialog-editor/components/modal/modalComponent.ts
  src/dialog-editor/components/toolbox/toolboxComponent.ts
  src/dialog-user/components/dialog-user/dialogField.html
  src/dialog-user/components/dialog-user/dialogUser.ts
  src/vendor.ts
Labels: gaprindashvili/yes, internationalization

#320 i18n string extraction & friends
  locale/ui-components.pot
  locale/zanata.xml
  package.json
  scripts/validate-gettext-catalog.js
  src/dialog-editor/components/box/box.html
Labels: enhancement, internationalization

#324 Update gettext catalog to include latest string fixes
  locale/ui-components.pot
Labels: gaprindashvili/no

#323 Sprintf and gettext fixes
  src/dialog-editor/components/modal/modalComponent.ts
  src/dialog-user/components/dialog-user/dialogUser.ts
  src/vendor.ts
Labels: bug, gaprindashvili/yes, internationalization

#325 [GAPRINDASHVILI] Update gettext catalog and zanata.xml for gaprindashvili branch
  locale/ui-components.pot
  locale/zanata.xml
Labels: internationalization

#326 Add translatable labels / titles for select and bs-switch
  src/dialog-editor/components/modal-field-template/check-box.html
  src/dialog-editor/components/modal-field-template/date-time-control.html
  src/dialog-editor/components/modal-field-template/drop-down-list.html
  src/dialog-editor/components/modal-field-template/fields-to-refresh.html
  src/dialog-editor/components/modal-field-template/radio-button.html
  src/dialog-editor/components/modal-field-template/tag-control.html
  src/dialog-editor/components/modal-field-template/text-area-box.html
  src/dialog-editor/components/modal-field-template/text-box.html
Labels: gaprindashvili/yes, internationalization

#318 fix refresh button placement in dialog show screen
  src/dialog-user/components/dialog-user/dialogField.html
Labels: bug, gaprindashvili/yes, ux/approved

#321 Verification for specified entry point in dynamic dropdown added
  src/dialog-editor/services/dialogValidationService.spec.ts
  src/dialog-editor/services/dialogValidationService.ts
Labels: bug

#319 Allow to parse a string with a floating point number
  src/dialog-user/services/dialogData.ts
Labels: bug, gaprindashvili/yes

#331 Update gettext catalog and catalog validation
  locale/ui-components.pot
  scripts/validate-gettext-catalog.js
  src/dialog-user/components/dialog-user/dialogField.html
Labels: gaprindashvili/no, internationalization

#332 [GAPRINDASHVILI] Update gettext string validation gettext fixes and update gettext catalog
  locale/ui-components.pot
  scripts/validate-gettext-catalog.js
  src/dialog-user/components/dialog-user/dialogField.html
Labels: internationalization

#334 Fix radio button styling
  src/dialog-editor/components/field/field.html
  src/dialog-user/components/dialog-user/dialogField.html
Labels: ux/review

#335 Add gettext:extract to travis build
  scripts/.build.sh
Labels: developer, gaprindashvili/yes

#333 Setting default value for unset bootstrap switches
  src/dialog-editor/services/dialogEditorService.ts
Labels: bug
