Repository ManageIQ/ui-components, pull requests merged in 2018-06, with the labels that each got.

#299 Prefix all angular-bootstrap directives with uib-
  src/dialog-editor/components/field/field.html
Labels: gaprindashvili/no, technical debt

#303 Added missing checkbox to allow load dynamic dialog values on init
  src/dialog-editor/components/modal-field-template/check-box.html
  src/dialog-editor/components/modal-field-template/text-area-box.html
  src/dialog-editor/components/modal-field-template/text-box.html
Labels: blocker, bug, gaprindashvili/yes

#304 Do not display cardview if no data available
  src/gtl/components/tile-view/tile-view.html
  src/gtl/interfaces/abstractDataViewClass.ts
  src/gtl/interfaces/dataTable.ts
Labels: bug, gaprindashvili/yes

#305 Extracted repeated code to a separate file
  src/dialog-editor/components/modal-field-template/check-box.html
  src/dialog-editor/components/modal-field-template/dynamic-values.html
  src/dialog-editor/components/modal-field-template/radio-button.html
  src/dialog-editor/components/modal-field-template/text-area-box.html
  src/dialog-editor/components/modal-field-template/text-box.html
Labels: refactoring

#306 Using separate file for repeated options
  src/dialog-editor/components/modal-field-template/drop-down-list.html
Labels: refactoring

#307 Do not sort dropdowns that have sort_by set to 'none'
  src/dialog-user/services/dialogData.spec.ts
  src/dialog-user/services/dialogData.ts
Labels: blocker, bug, gaprindashvili/yes

#309 Test that 'id' attribute is missing
  src/dialog-user/components/dialog-user/dialogField.ts
Labels: blocker

#310 Added a functionality to sort dropdown values manualy
  src/dialog-editor/components/modal-field-template/drop-down-list.html
  src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Labels: blocker, enhancement, gaprindashvili/yes

#312 Add to README.md where to find instruction to release ui-components
  README.md
Labels: documentation, gaprindashvili/no

#308 Remove the picture nodeIcon and prioritize the rest as image > icon
  src/gtl/components/data-table/data-table.html
  src/gtl/components/data-table/dataTableComponent.spec.ts
  src/gtl/components/data-table/dataTableComponent.ts
Labels: gaprindashvili/no
