Repository ManageIQ/ui-components, pull requests merged in 2019-05, with the labels that each got.

#383 [HAMMER] Force browser-sync to ~ instead of ^, fixes hammer travis
  package.json
  src/dialog-user/components/dialog-user/dialogField.spec.ts
Labels: test

#385 Dialog editor endpoint selection - fix badly named fqdn to fqname
  src/dialog-editor/components/modal-field/modalFieldComponent.ts
Labels: hammer/no, technical debt

#384 Replace 'values' key with 'default_value' when updating value for field
  src/dialog-user/components/dialog-user/dialogUser.spec.ts
  src/dialog-user/components/dialog-user/dialogUser.ts
Labels: bug

#386 Make sure main points to correct file
  package.json
Labels: changelog/no, hammer/no, technical debt

#389 Untangle numeral
  src/common/filters/abbrNumberFilter.ts
  src/vendor.ts
  webpack.config.js
  webpack.vendor.config.js
Labels: changelog/no, dependencies, hammer/no, technical debt

#390 Remove ui-select that is no longer used
  package.json
  src/dialog-user/index.ts
  src/styles/vendor.scss
  src/vendor.ts
Labels: changelog/no, dependencies, hammer/no

#388 Dialog editor - fix Validate switch undecided value
  src/dialog-editor/components/index.ts
  src/dialog-editor/components/modal-field-template/text-area-box.html
  src/dialog-editor/components/modal-field-template/text-box.html
  src/dialog-editor/components/validation/index.ts
  src/dialog-editor/components/validation/validation.html
  src/dialog-editor/components/validation/validation.ts
  src/dialog-editor/index.ts
Labels: bug, dialog editor
