Repository ManageIQ/ui-components, pull requests merged in 2019-04, with the labels that each got.

#378 Allow validator_rule to be updated in case of dynamic text boxes
  src/dialog-user/components/dialog-user/dialogField.spec.ts
  src/dialog-user/components/dialog-user/dialogUser.spec.ts
  src/dialog-user/components/dialog-user/dialogUser.ts
  src/dialog-user/services/dialogData.spec.ts
  src/dialog-user/services/dialogData.ts
Labels: bug, hammer/yes

#376 Dialog editor: Make "Load Values on Init" independent of "Show Refresh Button"
  src/dialog-editor/components/modal-field-template/dynamic-values.html
  src/dialog-editor/components/toolbox/toolboxComponent.ts
Labels: hammer/no

#380 Allow datepicker field in service dialogs to be set as required
  src/dialog-editor/components/modal-field-template/date-time-control.html
Labels: bug, hammer/yes

#381 Fix for dynamic dialog fields not being updated
  src/dialog-user/components/dialog-user/dialogField.html
  src/dialog-user/components/dialog-user/dialogField.ts
Labels: bug, hammer/yes

#382 Revert ng-model changes from #381
  src/dialog-user/components/dialog-user/dialogField.html
  src/dialog-user/components/dialog-user/dialogField.ts
Labels: blocker, bug, hammer/yes
