Repository ManageIQ/ui-components, pull requests merged in 2019-03, with the labels that each got.

#365 dialogField - move logic for setting default_value to one place
  src/dialog-user/components/dialog-user/dialogField.html
  src/dialog-user/components/dialog-user/dialogField.spec.ts
  src/dialog-user/components/dialog-user/dialogField.ts
  src/dialog-user/services/dialogData.ts
Labels: bug, gaprindashvili/yes, hammer/yes

#375 Fix travis - restrict bootstrap-select to ~1.12
  package.json
  src/dialog-user/components/dialog-user/dialogField.ts
Labels: dependencies, hammer/yes

#374 Fix linter issues in specs
  src/common/components/sortItemsComponent.spec.ts
  src/dialog-editor/services/dialogValidationService.spec.ts
  src/dialog-user/components/dialog-user/dialogUser.spec.ts
  src/dialog-user/services/dialogData.spec.ts
  src/gtl/components/data-table/dataTableComponent.spec.ts
  src/gtl/components/pagination/paginationComponent.spec.ts
  src/toolbar/components/toolbar-menu/toolbarClickDirective.spec.ts
  src/toolbar/components/toolbar-menu/toolbarKebabComponent.spec.ts
Labels: technical debt

#360 Return correct value from anyDialogFields
  src/dialog-editor/services/dialogEditorService.spec.ts
  src/dialog-editor/services/dialogEditorService.ts
Labels: bug, gaprindashvili/yes, hammer/yes

#370 Webpack.config - clean up formatting, support vim
  webpack.config.js
Labels: developer

#372 Squash tooltips from child elements in toolbar dropdown if disabled
  src/toolbar/components/toolbar-menu/toolbar-list.html
  src/toolbar/components/toolbar-menu/toolbarListComponent.ts
Labels: hammer/no, ux/review
