Repository ManageIQ/ui-components, pull requests merged in 2020-09, with the labels that each got.

#450 Fix at-loader failures in specs
  package.json
Labels: dependencies

#449 Fixed table header shift after icon column was removed from list view
  src/gtl/components/data-table/data-table.html
Labels: bug

#451 Correctly set null as default value for null and empty strings
  src/dialog-user/services/dialogData.ts
Labels: bug, dialog user, ivanchuk/yes, jansa/yes?

#452 Removed gtl and quadicon related files/code
  application-settings.js
  demo/controllers/dataTableController.ts
  demo/controllers/index.ts
  demo/controllers/quadiconController.ts
  demo/services/availableComponentsService.ts
  demo/views/data-table/basic.html
  demo/views/quadicon/basic.html
  demo/views/tile-view/big.html
  demo/views/tile-view/small.html
  src/gtl/components/data-table/data-table.html
  src/gtl/components/data-table/dataTableComponent.spec.ts
  src/gtl/components/data-table/dataTableComponent.ts
  src/gtl/components/data-table/index.ts
  src/gtl/components/index.ts
  src/gtl/components/pagination/index.ts
  src/gtl/components/pagination/pagination.html
  src/gtl/components/pagination/paginationComponent.spec.ts
  src/gtl/components/pagination/paginationComponent.ts
  src/gtl/components/pagination/paging.html
  src/gtl/components/pagination/pagingComponent.spec.ts
  src/gtl/components/pagination/pagingComponent.ts
  src/gtl/components/tile-view/index.ts
  src/gtl/components/tile-view/tile-view.html
  src/gtl/components/tile-view/tileViewComponent.spec.ts
  src/gtl/components/tile-view/tileViewComponent.ts
  src/gtl/filters/index.ts
  src/gtl/filters/limitToSuffixFilter.ts
  src/gtl/filters/limitToSufixFilter.spec.ts
  src/gtl/index.ts
  src/gtl/interfaces/abstractDataViewClass.ts
  src/gtl/interfaces/dataTable.ts
  src/gtl/interfaces/tileType.ts
  src/gtl/services/dataTableService.spec.ts
  src/gtl/services/dataTableService.ts
  src/gtl/services/index.ts
  src/gtl/toolbar-menu/index.ts
  src/gtl/toolbar-menu/toolbar-item-click.html
  src/gtl/toolbar-menu/toolbar-list.html
  src/gtl/toolbar-menu/toolbarClickDirective.spec.ts
  src/gtl/toolbar-menu/toolbarClickDirective.ts
  src/gtl/toolbar-menu/toolbarList.sample.json
  src/gtl/toolbar-menu/toolbarListComponent.spec.ts
  src/gtl/toolbar-menu/toolbarListComponent.ts
  src/index.ts
  src/quadicon/components/index.ts
  src/quadicon/components/quadicon/index.ts
  src/quadicon/components/quadicon/quadicon.html
  src/quadicon/components/quadicon/quadiconComponent.ts
  src/quadicon/components/quaditem/index.ts
  src/quadicon/components/quaditem/quaditem.html
  src/quadicon/components/quaditem/quaditemComponent.ts
  src/quadicon/index.ts
  src/styles/ui-components.scss
Labels: technical debt
