Repository ManageIQ/ui-components, pull requests merged in 2020-06, with the labels that each got.

#441 dialogData#validateField - fail validation when regex is not supported by browser
  src/dialog-user/services/dialogData.ts
  tslint.json
Labels: bug

#442 Don't set default value for non-applicable fields
  src/dialog-user/services/dialogData.ts
Labels: bug, ivanchuk/yes

#443 Add support for local validation of box, tab and field
  src/dialog-editor/components/abstractModal.ts
  src/dialog-editor/components/modal-box/box.html
  src/dialog-editor/components/modal-box/modalBoxComponent.ts
  src/dialog-editor/components/modal-field/field.html
  src/dialog-editor/components/modal-field/modalFieldComponent.ts
  src/dialog-editor/components/modal-tab/modalTabComponent.ts
  src/dialog-editor/components/modal-tab/tab.html
  src/dialog-editor/components/modal/modalComponent.ts
  src/dialog-editor/services/dialogValidationService.ts
Labels: dialog editor, enhancement
